
package it.unicas.server.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.ResponseBody;

import it.unicas.server.dao.UtenteDAO;
import it.unicas.server.model.Utente;

@Controller // This means that this class is a Controller
public class UtenteController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private UtenteDAO utenteDAO;

  @PostMapping(path="/add") // Map ONLY POST Requests
  public @ResponseBody Iterable<Utente> addNewUser(@RequestBody Utente collega) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request
	  utenteDAO.save(collega);
    return utenteDAO.findAll();
  }

  @GetMapping(path="/all")
  public @ResponseBody Iterable<Utente> getAllUsers() {
    // This returns a JSON or XML with the users
    return utenteDAO.findAll();
  }
}